version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - jokes-net
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - jokes-net
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  joke-service:
    build: .
    networks:
      - jokes-net
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  etl-service:
    build:
      context: .
      dockerfile: Dockerfile.etl
    networks:
      - jokes-net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  
  
  submit-service:
    build:
      context: ./submit  # Path to the directory containing the Dockerfile for submit-service
    networks:
      - jokes-net
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      # Add other environment variables as needed
    ports:
      - "3200:3200"  # Ensure this matches the port in your submit-server.js

  
  moderate-service:
    build: 
      context: ./moderate  # Path to the directory containing the Dockerfile for moderate-service
    networks:
      - jokes-net
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
    - ./moderate/backup-types.json:/usr/src/app/backup-types.json
    ports:
      - "3100:3100"
    depends_on:
      rabbitmq:
        condition: service_healthy


  # analytics-service:
  #   build:
  #     context: ./analytics  # Assuming your Analytics microservice Dockerfile is here
  #   environment:
  #     MONGO_URI: "mongodb://mongo:27017/analyticsDB"  # Update as per actual MongoDB URI
  #   ports:
  #     - "3300:3300"
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_DATABASE: "analyticsDB"
  #   volumes:
  #     - mongo-data:/data/db
  #   ports:
  #     - "27017:27017"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - mongo

  

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    networks:
      - jokes-net
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml
    depends_on:
      - joke-service
      - submit-service
      - moderate-service

  


networks:
  jokes-net:
    driver: bridge

volumes:
  db_data:
  rabbitmq_data:
  # mongo-data:
  
