version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jokesDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  joke-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
